apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=  # we should not pushed the credentials, just an example 
    mongo-root-password: cGFzc3dvcmQ=

